[project]
authors = ["0110tpwls <0110tpwls@gmail.com>"]
channels = ["https://prefix.dev/conda-forge", "conda-forge"]
description = "Baseline environment for LLM and lVLM"
name = "llm-baseline"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.4"

[tasks]

[dependencies]
python = "<=3.11"
pytorch-gpu = "*"
cuda-version = "12.4.*"
numpy = ">=1.26.0, <2"

[pypi-options]
no-build-isolation = ["flash-attn"]

[pypi-dependencies]
vllm = "*"
flash-attn = "*"
accelerate = ">=1.3.0, <2"
bitsandbytes = ">=0.45.2, <0.46"
